### ISSUE TITLE
reformat

### ISSUE THREAD

**Issue by sideria** [shivshankardayal/An-Angle-in-Trigonometry#3]
rewriting everything using LaTeX could be of great help for the readers

**Comment by shivshankardayal** [comment]
You can process Sphinx sources to produce LaTeX files though I agree to what you say. So I will rewrite in LaTeX.

**Comment by sideria** [comment]
glad you agree
how can i process the sphinx sources to produce LaTeX files? I'm not too familiar with how sphinx works

**Comment by shivshankardayal** [comment]
You will need a Python environment and LaTeX both. Once you have Python you can install dependencies by looking at conf.py and sphinx itself. Then in the root folder you can invoke `make latex` which will generate a `build/latex` folder which will contain the tex sources which can be processed. But rest assured that in the first run it will not work as there will be a LaTeX preamble needed in conf.py which will require extra packages. Also, the images in rst files are png and counterpart pdf extensions have to be provided.

**Comment by sideria** [comment]
ah thank you

**Comment by shivshankardayal** [comment]
You can watch https://github.com/shivshankardayal/Trigonometry-Latex repo which will contain LaTeX source.

**Comment by shivshankardayal** [comment]
Also, there is a book on Algebra which I will convert first. I will make the repo as https://github.com/shivshankardayal/Algebra-Latex
